import { colors } from '@nptech/styles'

export const dark = {
  colors: {
    background: `${colors.darkGrey}`,
    navbar: `${colors.lightGrey}`,
    text: `${colors.white}`,
    yellow: `${colors.yellow}`,
    extraBBackground: `${colors.yellow}`,
    extraText: `${colors.darkGrey}`,
    ctaText: `${colors.white}`,
    ctaTextExtra: `${colors.yellow}`,
    anchorButtonText: `${colors.darkGrey}`,
    anchorButtonBackground: `${colors.yellow}`,
    sectionTitle: `${colors.yellow}`,
    sectionTitleText: `${colors.white}`,
    sectionTitleShadow: `${colors.darkGrey}`,
    sectionTitleUnderline: `${colors.yellow}`,
    formFont: `${colors.yellow}`,
    formLine: `${colors.lightGrey}`,
    formInput: `${colors.white}`,
    sideBar: `${colors.black}`,
    sideBarText: `${colors.white}`,
    projectTitle: `${colors.yellow}`,
    projectText: `${colors.white}`,
    projectTechText: `${colors.darkGrey}`,
    projectTechBackground: `${colors.yellow}`,
    linkButtonBackground: `${colors.yellow}`,
    linkButtonText: `${colors.lightGrey}`,
    linkButtonTextHover: `${colors.darkGrey}`,
    footerColor: `${colors.lightGrey}`,
    footerBackground: `${colors.darkGrey}`,
    messageColor: `${colors.darkGrey}`,
    messageBackground: `${colors.yellow}`,
  },
}

// TODO -> LIGHT THEME
export const light = {
  colors: {
    background: '',
    navbar: `${colors.white}`,
    text: '',
    yellow: `${colors.yellow}`,
    extraBBackground: '',
    extraText: '',
    ctaText: '',
    ctaTextExtra: '',
    anchorButtonText: '',
    anchorButtonBackground: '',
    sectionTitle: '',
    sectionTitleText: '',
    sectionTitleUnderline: '',
    formFont: '',
    formLine: '',
    formInput: '',
    sideBar: '',
    sideBarText: '',
    projectTitle: '',
    projectText: '',
    projectTechText: '',
    projectTechBackground: '',
    linkButtonBackground: '',
    linkButtonText: '',
    footerColor: ``,
    footerBackground: ``,
    messageColor: '',
    messageBackground: '',
  },
}
