name: Release Workflow

on:
  push:
    tags:
      - '*'

jobs:
  installing:
    name: Running Release Worflow
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Running install ...
        run: yarn

      - name: Running linters ...
        run: yarn lint

      - name: Running tests ...
        run: yarn test

      - name: Triggering Deploy ...
        run: curl -POST ${{ secrets.VERCEL_MASTER_RELEASE }}
